import React from 'react';
export const metadata = {
  title: "Stats",
  description: "Generated by create next app",
};
const Stats = () => {
    return (
        <div>
            this is a state
        </div>
    );
};

export default Stats;