import React from 'react';
export const metadata = {
  title: "TimeLine",
  description: "Generated by create next app",
};
const TimeLine = () => {
    return (
        <div>
            this is time line
        </div>
    );
};

export default TimeLine;